In [8]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 10)

In [2]:
produits = pd.read_excel("composition-nutritionnelle.xls", index_col=[0],usecols=[6,7,12,13,15,16,17,18])

In [3]:
# faisons une copie de notre DataFrame
copieProd = produits.copy()

In [4]:
copieProd.head()

,alim_nom_fr,Eau (g/100g),Protéines (g/100g),Glucides (g/100g),Lipides (g/100g),Sucres (g/100g),Amidon (g/100g)
alim_code,,,,,,,
25600,"Céleri rémoulade, préemballé","78,5","1,12","4,19","12,8","2,38","1,3"
25601,"Salade de thon et légumes, appertisée, égouttée","76,5","9,15","7,74","4,7","3,08","4,1"
25602,"Salade composée avec viande ou poisson, appert...","76,7","8,06","6,4","5,3","1,9","3,3"
25605,Champignon à la grecque,"84,6","2,08","3,95","3,55","2,38","0,28"
25606,Salade de pommes de terre maison,76,"2,68","9,9","8,2",-,-

In [5]:
copieProd['Eau (g/100g)']=copieProd['Eau (g/100g)']+" gr"

In [6]:
copieProd.head()

,alim_nom_fr,Eau (g/100g),Protéines (g/100g),Glucides (g/100g),Lipides (g/100g),Sucres (g/100g),Amidon (g/100g)
alim_code,,,,,,,
25600,"Céleri rémoulade, préemballé","78,5 gr","1,12","4,19","12,8","2,38","1,3"
25601,"Salade de thon et légumes, appertisée, égouttée","76,5 gr","9,15","7,74","4,7","3,08","4,1"
25602,"Salade composée avec viande ou poisson, appert...","76,7 gr","8,06","6,4","5,3","1,9","3,3"
25605,Champignon à la grecque,"84,6 gr","2,08","3,95","3,55","2,38","0,28"
25606,Salade de pommes de terre maison,76 gr,"2,68","9,9","8,2",-,-