In [25]:
import pandas as pd
pd.core.common.is_list_like = pd.api.types.is_list_like

import pandas_datareader.data as web
import datetime as dt

In [46]:
action= '^DJI'
action="TSLA"
source = 'stooq'
source ="morningstar"
depuis = "2015-01-01"
jusqua = "2018-08-21"
depuis = dt.date(2015, 2, 9)
jusqua =  dt.date(2018, 8, 18)

#df = web.DataReader(name=action,data_source=source,start=depuis,end=jusqua)

#df = web.DataReader(name=action,data_source='google',start=depuis,end=jusqua)
#df2 = web.DataReader("google",source,depuis,jusqua)
#action=web.DataReader('USD000UTSTOM', 'moex', start=depuis, end=jusqua)
action=web.DataReader('^DJI', 'stooq')

In [47]:
action.index

DatetimeIndex(['2018-08-20', '2018-08-17', '2018-08-16', '2018-08-15',
               '2018-08-14', '2018-08-13', '2018-08-10', '2018-08-09',
               '2018-08-08', '2018-08-07',
               ...
               '1896-06-09', '1896-06-08', '1896-06-05', '1896-06-04',
               '1896-06-03', '1896-06-02', '1896-06-01', '1896-05-29',
               '1896-05-28', '1896-05-27'],
              dtype='datetime64[ns]', name='Date', length=31694, freq=None)

In [49]:
action

                Open      High       Low     Close       Volume
Date
2018-08-20  25727.70  25790.17  25716.41  25758.69          NaN
2018-08-17  25550.80  25728.16  25521.66  25669.32   81028248.0
2018-08-16  25294.97  25607.34  25294.97  25558.73   85374528.0
2018-08-15  25235.37  25235.37  24965.77  25162.41   79783352.0
2018-08-14  25215.69  25339.51  25201.87  25299.92   57509176.0
2018-08-13  25327.19  25381.39  25153.93  25187.70   64198680.0
2018-08-10  25401.19  25401.19  25222.88  25313.14   60954752.0
2018-08-09  25589.79  25613.31  25492.69  25509.23   59553920.0
2018-08-08  25615.72  25634.11  25557.48  25583.75   60567820.0
2018-08-07  25551.65  25692.72  25551.65  25628.91   64961976.0
2018-08-06  25437.43  25540.02  25381.38  25502.18   66822708.0
2018-08-03  25360.37  25467.90  25325.17  25462.58   67528456.0
2018-08-02  25256.45  25360.48  25120.07  25326.16   81618136.0
2018-08-01  25461.63  25488.80  25278.32  25333.82   82420312.0
2018-07-31  25345.21  25490.98  25345.21  25415.19  128328728.0
2018-07-30  25439.32  25500.16  25287.38  25306.83   84874728.0
2018-07-27  25520.52  25580.22  25370.07  25451.06   93887224.0
2018-07-26  25468.55  25587.24  25463.16  25527.07   95788672.0
2018-07-25  25183.70  25432.87  25113.55  25414.10   92419160.0
2018-07-24  25092.43  25286.62  25092.43  25241.94   85381312.0
2018-07-23  25036.90  25081.45  24983.33  25044.29   80936168.0
2018-07-20  25041.14  25124.10  24986.35  25058.12  121151336.0
2018-07-19  25139.15  25154.17  25052.62  25064.50   88748160.0
2018-07-18  25133.79  25215.32  25101.12  25199.29   76769264.0
2018-07-17  25033.92  25155.39  24989.61  25119.89   82149760.0
2018-07-16  25025.58  25072.41  24979.64  25064.36   78903152.0
2018-07-13  24926.07  25043.21  24890.06  25019.41   78989320.0
2018-07-12  24802.90  24939.97  24802.90  24924.89   78658616.0
2018-07-11  24789.48  24815.16  24663.82  24700.45   77924224.0
2018-07-10  24806.97  24945.38  24806.97  24919.66   78618376.0
...              ...       ...       ...       ...          ...
1896-07-07     25.46     25.46     25.46     25.46          NaN
1896-07-06     25.25     25.25     25.25     25.25          NaN
1896-07-03     25.16     25.16     25.16     25.16          NaN
1896-07-02     25.28     25.28     25.28     25.28          NaN
1896-07-01     25.05     25.05     25.05     25.05          NaN
1896-06-30     26.18     26.18     26.18     26.18          NaN
1896-06-29     25.73     25.73     25.73     25.73          NaN
1896-06-26     27.44     27.44     27.44     27.44          NaN
1896-06-25     27.50     27.50     27.50     27.50          NaN
1896-06-24     27.72     27.72     27.72     27.72          NaN
1896-06-23     27.62     27.62     27.62     27.62          NaN
1896-06-22     28.05     28.05     28.05     28.05          NaN
1896-06-19     28.99     28.99     28.99     28.99          NaN
1896-06-18     28.80     28.80     28.80     28.80          NaN
1896-06-17     29.36     29.36     29.36     29.36          NaN
1896-06-16     29.30     29.30     29.30     29.30          NaN
1896-06-15     28.92     28.92     28.92     28.92          NaN
1896-06-12     28.47     28.47     28.47     28.47          NaN
1896-06-11     28.54     28.54     28.54     28.54          NaN
1896-06-10     27.82     27.82     27.82     27.82          NaN
1896-06-09     28.49     28.49     28.49     28.49          NaN
1896-06-08     28.83     28.83     28.83     28.83          NaN
1896-06-05     29.20     29.20     29.20     29.20          NaN
1896-06-04     28.93     28.93     28.93     28.93          NaN
1896-06-03     28.80     28.80     28.80     28.80          NaN
1896-06-02     29.00     29.00     29.00     29.00          NaN
1896-06-01     29.40     29.40     29.40     29.40          NaN
1896-05-29     29.43     29.43     29.43     29.43          NaN
1896-05-28     29.11     29.11     29.11     29.11          NaN
1896-05-27     29.39     29.39     29.39     29.39          NaN

[31694 rows x 5 columns]

In [52]:
action.sort_index(inplace=True)

In [54]:
action.loc["2018-01-01":"2018-08-01"]

                Open      High       Low     Close       Volume
Date
2018-01-02  24809.35  24864.19  24741.70  24824.01   93837856.0
2018-01-03  24850.45  24941.92  24825.55  24922.68  113120472.0
2018-01-04  24964.86  25105.96  24963.27  25075.13  101492432.0
2018-01-05  25114.92  25299.79  25112.01  25295.87   99171640.0
2018-01-08  25308.40  25311.99  25235.41  25283.00   97611920.0
2018-01-09  25312.05  25439.78  25308.41  25385.80   88515640.0
2018-01-10  25348.13  25404.92  25256.99  25369.13   88364144.0
2018-01-11  25398.60  25575.42  25396.19  25574.73   90362032.0
2018-01-12  25638.39  25810.43  25633.08  25803.19  103878720.0
2018-01-16  25987.62  26086.12  25702.99  25792.86  171084224.0
2018-01-17  25910.78  26130.45  25865.02  26115.65  133700112.0
2018-01-18  26149.55  26153.42  25947.32  26017.81  122449616.0
2018-01-19  25987.35  26071.72  25942.83  26071.72  171541424.0
2018-01-22  26025.32  26215.23  25974.65  26214.60  126357768.0
2018-01-23  26214.87  26246.19  26143.90  26210.81  109272288.0
2018-01-24  26282.07  26392.80  26106.94  26252.12  123271104.0
2018-01-25  26313.06  26458.25  26259.72  26392.79   95732448.0
2018-01-26  26466.74  26616.71  26425.35  26616.71  123610888.0
2018-01-29  26584.28  26608.90  26435.34  26439.48  110919888.0
2018-01-30  26198.45  26256.99  26028.42  26076.89  111840144.0
2018-01-31  26268.17  26338.03  26050.98  26149.39  140120144.0
2018-02-01  26083.04  26306.70  26014.44  26186.71  111586352.0
2018-02-02  26061.79  26061.79  25490.66  25520.96  140879408.0
2018-02-05  25337.87  25520.53  23923.88  24345.75  210835440.0
2018-02-06  24085.17  24946.23  23778.74  24912.77  231326304.0
2018-02-07  24892.87  25293.96  24785.44  24893.35  146600464.0
2018-02-08  24902.30  24903.68  23849.23  23860.46  179770672.0
2018-02-09  23992.67  24382.14  23360.29  24190.90  198760880.0
2018-02-12  24337.76  24765.16  24290.48  24601.27  149693824.0
2018-02-13  24540.33  24705.72  24421.03  24640.45   99077712.0
...              ...       ...       ...       ...          ...
2018-06-20  24771.17  24804.76  24628.39  24657.80   93328952.0
2018-06-21  24639.21  24639.21  24406.63  24461.70   91342448.0
2018-06-22  24526.97  24663.18  24526.97  24580.89  187244800.0
2018-06-25  24463.73  24463.73  24084.39  24252.80  126956384.0
2018-06-26  24281.89  24384.21  24241.22  24283.11  124961888.0
2018-06-27  24303.11  24569.02  24115.82  24117.59  117435992.0
2018-06-28  24064.19  24308.16  23997.21  24216.05   95902528.0
2018-06-29  24323.93  24509.52  24269.71  24271.41  126101120.0
2018-07-02  24161.53  24319.42  24077.56  24307.18   91452984.0
2018-07-03  24359.39  24444.88  24150.85  24174.82   64243968.0
2018-07-05  24285.82  24372.80  24177.44  24356.74   88005704.0
2018-07-06  24352.47  24520.29  24281.47  24456.48   84739696.0
2018-07-09  24525.23  24796.29  24525.23  24776.59   80515008.0
2018-07-10  24806.97  24945.38  24806.97  24919.66   78618376.0
2018-07-11  24789.48  24815.16  24663.82  24700.45   77924224.0
2018-07-12  24802.90  24939.97  24802.90  24924.89   78658616.0
2018-07-13  24926.07  25043.21  24890.06  25019.41   78989320.0
2018-07-16  25025.58  25072.41  24979.64  25064.36   78903152.0
2018-07-17  25033.92  25155.39  24989.61  25119.89   82149760.0
2018-07-18  25133.79  25215.32  25101.12  25199.29   76769264.0
2018-07-19  25139.15  25154.17  25052.62  25064.50   88748160.0
2018-07-20  25041.14  25124.10  24986.35  25058.12  121151336.0
2018-07-23  25036.90  25081.45  24983.33  25044.29   80936168.0
2018-07-24  25092.43  25286.62  25092.43  25241.94   85381312.0
2018-07-25  25183.70  25432.87  25113.55  25414.10   92419160.0
2018-07-26  25468.55  25587.24  25463.16  25527.07   95788672.0
2018-07-27  25520.52  25580.22  25370.07  25451.06   93887224.0
2018-07-30  25439.32  25500.16  25287.38  25306.83   84874728.0
2018-07-31  25345.21  25490.98  25345.21  25415.19  128328728.0
2018-08-01  25461.63  25488.80  25278.32  25333.82   82420312.0

[147 rows x 5 columns]